name: Wheels

on:
  workflow_dispatch:
    inputs:
      overrideVersion:
        description: Manually force a version
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master
  release:
    types:
      - published


env:
  SETUPTOOLS_SCM_PRETEND_VERSION: ${{ github.event.inputs.overrideVersion }}
  CIBW_TEST_EXTRAS: test
  CIBW_TEST_COMMAND: "pytest {project}/tests"


jobs:

  build_arch_wheels:
    name: ${{ matrix.arch }} wheels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, s390x, ppc64le]

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: actions/setup-python@v2

    - uses: henryiii/cibuildwheel@feat/archgha
      with:
        archs: ${{ matrix.arch }}

    - name: Show files
      run: ls -lh wheelhouse
      shell: bash

    - name: Verify clean directory
      run: git diff --exit-code
      shell: bash

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        path: wheelhouse/*.whl
